### PR TITLE
Now working in OS X

### PR DESCRIPTION
**Pull request by Jeff-Russ**
The AU plugin loads without any known issues in Logic Pro X, Reaper and Ableton Live 9, The VST is the same story only sans Logic Pro X which can't use VST's.

### CODE REVIEW

**Comment by bsutherland** [comment]
Thanks a lot Jeff! I'll attempt to merge it on the weekend and make sure
it's still building OK on Windows.

**Comment by Jeff-Russ** [comment]
I posted a link to my gh-pages on a few chiptune forums fishing for testers and it's been hit so far! One person wanted to know how to donate to the dev and I directed him to your github page. If you have paypal info I'll pass it along to him in case he can't contact you via github.

**Comment by bsutherland** [comment]
Jeffrey,

Thanks a lot for spreading the word! Could you please send me some links to
the forums?

Unfortunately I had computer trouble of the smoky kind on the weekend.

When I have a working PC I will merge your code. For now its smartphone
only :(

Bruce

Cheers,

Bruce

**Comment by Jeff-Russ** [comment]
Ah! Sorry to hear that!
https://www.facebook.com/groups/chiptuneswin/search/?query=adlibblaster

**Comment by bsutherland** [comment]
Hey, I finally got a new PC sorted out :) Hopefully I'll get some time to merge and build on the weekend. I thought Apple had Boot Camp to allow you to install Windows too?

**Comment by Jeff-Russ** [comment]
Great! It does have boot camp but most people use VMWare so they go circle around Windows/LinuxMac without rebooting. Hit command-space and type "boot camp assistant."

**Comment by Jeff-Russ** [comment]
Great! It does have boot camp but most people use VMWare so they go circle around Windows/LinuxMac without rebooting.

**Comment by bsutherland** [comment]
Jeff,

I finally merged your pull-request. I'm really sorry for taking such a long time!
I had to tweak the typedefs in config.h to get it building in VIsual Studio on my machine again.
Hopefully it didn't break the Apple build, but unfortunately I have no way to verify :(

Thanks again for your help!

Bruce

**Pull request merged**
