### PR TITLE
fix 3 compile errors (2 Xcode 1 projucer) and some warnings

### PR DESCRIPTION
**Pull request by jrrs**
compiles on xcode 10.0 and projucer 5.3.2

### CODE REVIEW

**Comment by bsutherland** [comment]
Awesome, thanks for the contribution! Please give me some time to check this builds under Windows. Definitely want to merge this in, but I'm flat out with work and away over the weekend. Thanks again.

**Comment by jrrs** [comment]
<3

so far i’ve seen it working well for me on OSX

i’m not very conversant C++ and largely was applying fixes based on help
text in the IDEs and googling.

another thing i was curious about. line 292 of DROMultiplexer.cpp has an “i
< i” conditional in the for loop. idk if the body of the loop ever fires?

**Comment by bsutherland** [comment]
Hi jrrs. Thanks again for the fixes. I manually applied most of them in master, and confirmed that it builds under Windows. The rest of them seem to be differences in the .jucer file generated by ProJucer, or whitespace changes? Please let me know if I'm wrong there.

Does the master branch build for you now under OSX? If so, could I please ask you to upload a binary here so that others on OSX can use it?

**Comment by YarlBoro** [comment]
Hi!
First let me thank for JUCEOPLVSTi creation. It is one of my favourite instruments since I've found it one year ago. For my ears, nothing sounds like OPL :)

I managed to compile version 1.0 in AU format on MacOS. I had to correct only one major bug breaking compilation under XCode. File 'juce_audio_basics.h' was improperly linked. I managed to correct it by pointing XCode to this file location on my drive (I used UI, not code). Maybe JRRS can do something about it, I'm clueless non-programmer. 
Compilation shows some non-critical errors, screenshot below. Plugin is properly detected & works under Ableton Live 10. My own .SBI presets that I created with older version of JUCEOPLVSTi (14.2) sound as they did before. All new elements of UI seem to work properly. Thats all I can say after few minutes of fooling around with this new version.

Here is my AU binary:
[JuceOPLVSTi.component.zip](https://github.com/bsutherland/JuceOPLVSTi/files/2526291/JuceOPLVSTi.component.zip)

Here is screenshot of bugs reported during compilation (XCode 9.2, MacOS 10.12.6):
aaa_xcode_errors

**Comment by jrrs** [comment]
thanks guys! i’ll check this out soon

**Comment by bsutherland** [comment]
Closing because the changes were merged manually. Thanks for your contributions.

**Pull request closed without merging**
